on : [push]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
     - name: ZAP Scan v050
       uses: zaproxy/action-baseline@v0.5.0
       with:
           target: 'https://www.zaproxy.org'
        
