name: ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ZAP
        run: |
          curl -LO https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2.12.0_Core.zip
          unzip ZAP_2.12.0_Core.zip
          chmod +x ZAP_2.10.0/zap.sh

      - name: Start ZAP
        run: ./ZAP_2.10.0/zap.sh -daemon -port 8080

      - name: Import Swagger file
        run: zap-cli openapi.load https://petstore.swagger.io/v2/swagger.json

      - name: Spider API endpoints
        run: zap-cli active_scan.scan -r "Default Policy" -G https://petstore.swagger.io/v2/swagger.json

      - name: Wait for scan completion
        run: |
          while [[ $(zap-cli active_scan.status) == *"running"* ]]; do
            sleep 10
          done

      - name: Generate ZAP report
        run: zap-cli report -o zap_report.html -f html

      - name: Stop ZAP
        run: zap-cli shutdown
